export type LegalSection = { heading: string; paragraphs: string[] };

export const LEGAL_CONTENT = {
  terms: {
    title: "Terms of Service",
    sections: [
      {
        heading: "Acceptance",
        paragraphs: [
          "By accessing or using MergN, you agree to these Terms of Service. If you do not agree, do not use the service.",
        ],
      },
      {
        heading: "The service",
        paragraphs: [
          "MergN is a workflow automation platform. You can design workflows visually, build and edit them with an AI assistant, connect third-party services, upload files, run workflows manually or on a schedule, and trigger them via webhooks.",
        ],
      },
      {
        heading: "Accounts",
        paragraphs: [
          "You must provide accurate information when creating an account. You are responsible for keeping your credentials secure and for all activity under your account.",
        ],
      },
      {
        heading: "Acceptable use",
        paragraphs: [
          "You agree not to use MergN for unlawful purposes, to attempt unauthorized access to our systems or other users' data, to abuse rate limits or overload the service, or to upload content that infringes others' rights or contains malware.",
          "Do not paste API keys, passwords, or other secrets into chat. Use the Connections panel so credentials are stored in the vault instead.",
        ],
      },
      {
        heading: "Your content",
        paragraphs: [
          "You retain ownership of workflows, files, and other data you create. You grant us permission to host, process, and transmit that content as needed to operate the service — including sending relevant portions to AI model providers and executing workflow steps against third-party APIs you connect.",
          "You are responsible for having the right to upload and process any data in your workflows, and for complying with the terms of any third-party services you integrate.",
        ],
      },
      {
        heading: "AI-generated output",
        paragraphs: [
          "Workflow definitions, step code, and chat responses may be generated by AI and can contain errors. Review and test automations before relying on them in production.",
        ],
      },
      {
        heading: "Plans and billing",
        paragraphs: [
          "Usage limits may apply depending on your plan (for example, monthly chat or AI token limits). Paid subscriptions are processed through Stripe. You can manage or cancel your subscription through the billing portal.",
        ],
      },
      {
        heading: "Webhooks",
        paragraphs: [
          "Webhook triggers can optionally be protected with a secret token. When enabled, incoming requests must include a valid token or they are rejected. When disabled, anyone who knows the webhook URL can invoke the workflow.",
          "You choose whether to enable authentication for each webhook. If you enable it, you are responsible for keeping the secret secure and configuring the sending service to include it on every request. If you leave it disabled, treat the webhook URL as confidential.",
        ],
      },
      {
        heading: "Disclaimer",
        paragraphs: [
          "The service is provided \"as is\" without warranties of any kind. To the fullest extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from your use of the service, workflow failures, AI output, or third-party integrations.",
        ],
      },
      {
        heading: "Changes",
        paragraphs: [
          "We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the updated terms.",
        ],
      },
      {
        heading: "Contact",
        paragraphs: ["Questions about these terms: hq@flowbaker.io"],
      },
    ] satisfies LegalSection[],
  },
  privacy: {
    title: "Privacy Policy",
    sections: [
      {
        heading: "Overview",
        paragraphs: [
          "This policy describes how MergN collects, uses, and stores information when you use our hosted service. It applies to data processed on our servers on your behalf.",
        ],
      },
      {
        heading: "Account information",
        paragraphs: [
          "When you register, we collect your email address, password, and optionally your name. Passwords are hashed by our authentication system (Better Auth) and are not stored in plain text.",
          "If social login is enabled, we may receive basic profile information (such as email and name) from Google or GitHub through OAuth.",
          "We use session cookies to keep you signed in. Your browser may also store cached account info (id, email, name), your active workspace id, theme preference, and language preference in localStorage.",
        ],
      },
      {
        heading: "Workflow and workspace data",
        paragraphs: [
          "We store workspaces tied to your account, including workflow definitions (step code, wiring, triggers, variables, and configuration), AI chat conversations (your messages and assistant responses), and workflow run records (inputs, step outputs, errors, and status).",
          "Chat messages are scoped to your user account within each workspace. User messages may be truncated before being sent to AI providers.",
        ],
      },
      {
        heading: "Files",
        paragraphs: [
          "Files you upload are stored with metadata (name, type, size, and source). File content may be read by the AI assistant or injected into workflow steps when you reference them.",
        ],
      },
      {
        heading: "Connection credentials",
        paragraphs: [
          "When you connect third-party services via API keys or OAuth, secret values are stored in a separate vault — not in workflow documents or chat history. We store connection metadata separately (provider, account label, scopes, expiry).",
          "On our managed deployment, secrets may be encrypted at rest. Secret values are never returned to your browser or included in AI chat context.",
        ],
      },
      {
        heading: "Usage and billing data",
        paragraphs: [
          "We track per-workspace monthly usage, including new chat conversations and AI token consumption, to enforce plan limits.",
          "If you subscribe to a paid plan, we use Stripe for billing. We store Stripe customer and subscription identifiers and plan status locally. Payment details are handled by Stripe under its own privacy policy.",
        ],
      },
      {
        heading: "Logs",
        paragraphs: [
          "We maintain a rolling log of recent events per workspace (up to 500 entries), including build, run, chat, system, and client-reported messages. Individual log messages and details are length-capped.",
        ],
      },
      {
        heading: "Product analytics",
        paragraphs: [
          "We use PostHog to collect product analytics on our hosted service. This may include page views, page navigation, session duration, and basic device or browser information (such as user agent and screen size).",
          "PostHog data helps us understand how the product is used and improve the service. Analytics are processed by PostHog (US cloud). See PostHog's privacy policy at https://posthog.com/privacy for how they handle data.",
          "We do not use PostHog to sell your data or for third-party advertising. Identified user profiles in PostHog are created only when you are signed in and we associate analytics with your account.",
        ],
      },
      {
        heading: "AI and third-party processing",
        paragraphs: [
          "Your chat messages, workflow definitions, file excerpts (when referenced), error details, and related context are sent to configured AI model providers (such as Google Gemini, OpenAI, or Anthropic) to power chat, workflow authoring, and repair features.",
          "Workflow steps you configure may call third-party APIs using credentials you provide (for example Slack, GitHub, or custom integrations).",
          "We do not sell your personal data. On managed deployments, optional AI tracing (Langfuse) may be enabled to monitor model performance; when enabled, traces may include workspace identifiers and session ids.",
          "We use infrastructure providers necessary to operate the service, including document storage (MongoDB), optional object storage for files and secrets, NATS for job scheduling, and optional HashiCorp Vault for encryption.",
        ],
      },
      {
        heading: "Data retention and deletion",
        paragraphs: [
          "Data persists until you delete it (workflows, conversations, files) or request account deletion. There is no automatic expiry. Contact us to request deletion of your account and associated data.",
        ],
      },
      {
        heading: "Security",
        paragraphs: [
          "We use authenticated sessions, workspace isolation, and separate vault storage for credentials. Webhook triggers optionally support secret-token authentication, which you can enable per workflow.",
        ],
      },
      {
        heading: "Your rights",
        paragraphs: [
          "Depending on your jurisdiction, you may have rights to access, correct, or delete your personal data. Contact us at hq@flowbaker.io.",
        ],
      },
      {
        heading: "Changes",
        paragraphs: [
          "We may update this policy from time to time. Continued use of the service after changes are posted constitutes acceptance.",
        ],
      },
      {
        heading: "Contact",
        paragraphs: ["Privacy questions: hq@flowbaker.io"],
      },
    ] satisfies LegalSection[],
  },
} as const;
